"""Template manager for certificate generation."""

import os
from pathlib import Path
from typing import Dict, List, Optional
from config.settings import settings


class TemplateManager:
    """Manager for certificate templates (vars files)."""

    def __init__(self, template_dir: Optional[str] = None):
        """Initialize template manager.

        Args:
            template_dir: Template directory path (default from settings)
        """
        self.template_dir = template_dir or settings.template_dir

    def list_templates(self) -> List[str]:
        """List available templates.

        Returns:
            List of template names (without .vars extension)
        """
        template_path = Path(self.template_dir)

        if not template_path.exists():
            return []

        templates = []
        for vars_file in template_path.glob('*.vars'):
            templates.append(vars_file.stem)

        return sorted(templates)

    def load_template(self, template_name: str) -> Dict[str, str]:
        """Load template variables.

        Args:
            template_name: Template name (without .vars extension)

        Returns:
            Dictionary of template variables
        """
        template_path = Path(self.template_dir) / f'{template_name}.vars'

        if not template_path.exists():
            return {}

        variables = {}

        try:
            with open(template_path, 'r') as f:
                for line in f:
                    line = line.strip()

                    # Skip comments and empty lines
                    if not line or line.startswith('#'):
                        continue

                    # Parse set_var lines
                    if line.startswith('set_var '):
                        parts = line[8:].split(None, 1)
                        if len(parts) == 2:
                            key = parts[0]
                            value = parts[1].strip().strip('"\'')
                            variables[key] = value

                    # Parse export lines
                    elif line.startswith('export '):
                        parts = line[7:].split('=', 1)
                        if len(parts) == 2:
                            key = parts[0].strip()
                            value = parts[1].strip().strip('"\'')
                            variables[key] = value

        except Exception as e:
            print(f'Error loading template: {e}')

        return variables

    def save_template(self, template_name: str, variables: Dict[str, str]) -> bool:
        """Save template variables to file.

        Args:
            template_name: Template name (without .vars extension)
            variables: Dictionary of variables

        Returns:
            True if saved successfully
        """
        template_path = Path(self.template_dir)
        template_path.mkdir(parents=True, exist_ok=True)

        vars_file = template_path / f'{template_name}.vars'

        try:
            with open(vars_file, 'w') as f:
                f.write(f'# Easy-RSA template: {template_name}\n')
                f.write(f'# Auto-generated by Easy-RSA PyTk\n\n')

                for key, value in sorted(variables.items()):
                    # Quote values with spaces
                    if ' ' in str(value):
                        f.write(f'set_var {key} "{value}"\n')
                    else:
                        f.write(f'set_var {key} {value}\n')

            return True

        except Exception as e:
            print(f'Error saving template: {e}')
            return False

    def delete_template(self, template_name: str) -> bool:
        """Delete a template.

        Args:
            template_name: Template name to delete

        Returns:
            True if deleted successfully
        """
        template_path = Path(self.template_dir) / f'{template_name}.vars'

        try:
            if template_path.exists():
                template_path.unlink()
                return True
            return False
        except Exception as e:
            print(f'Error deleting template: {e}')
            return False

    def merge_template(self, template_name: str, overrides: Dict[str, str]) -> Dict[str, str]:
        """Merge template with override values.

        Args:
            template_name: Base template name
            overrides: Values to override

        Returns:
            Merged dictionary
        """
        variables = self.load_template(template_name)
        variables.update(overrides)
        return variables

    def generate_vars_file(self, output_path: str, variables: Dict[str, str]) -> bool:
        """Generate vars file from variables.

        Args:
            output_path: Path to write vars file
            variables: Dictionary of variables

        Returns:
            True if generated successfully
        """
        try:
            output_file = Path(output_path)
            output_file.parent.mkdir(parents=True, exist_ok=True)

            with open(output_file, 'w') as f:
                f.write('# Easy-RSA variables file\n')
                f.write('# Generated by Easy-RSA PyTk\n\n')

                for key, value in sorted(variables.items()):
                    if ' ' in str(value):
                        f.write(f'set_var {key} "{value}"\n')
                    else:
                        f.write(f'set_var {key} {value}\n')

            return True

        except Exception as e:
            print(f'Error generating vars file: {e}')
            return False

    def get_default_variables(self) -> Dict[str, str]:
        """Get default variables for a new certificate.

        Returns:
            Dictionary of default variables
        """
        return {
            'EASYRSA_REQ_COUNTRY': 'US',
            'EASYRSA_REQ_PROVINCE': 'State',
            'EASYRSA_REQ_CITY': 'City',
            'EASYRSA_REQ_ORG': 'Organization',
            'EASYRSA_REQ_EMAIL': 'admin@example.com',
            'EASYRSA_REQ_OU': 'IT',
            'EASYRSA_KEY_SIZE': '2048',
            'EASYRSA_CERT_EXPIRE': '825',
            'EASYRSA_CA_EXPIRE': '3650'
        }

    def import_template_from_file(self, source_file: str, template_name: str) -> bool:
        """Import template from external file.

        Args:
            source_file: Source vars file path
            template_name: Name for imported template

        Returns:
            True if imported successfully
        """
        if not os.path.exists(source_file):
            return False

        try:
            # Load from source
            variables = {}
            with open(source_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue

                    if line.startswith('set_var '):
                        parts = line[8:].split(None, 1)
                        if len(parts) == 2:
                            key = parts[0]
                            value = parts[1].strip().strip('"\'')
                            variables[key] = value

            # Save as template
            return self.save_template(template_name, variables)

        except Exception as e:
            print(f'Error importing template: {e}')
            return False
